apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-uploads
  labels:
    {{- include "ticketdesk.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
  {{- if .Values.persistence.uploads.storageClass }}
  storageClassName: {{ .Values.persistence.uploads.storageClass }}
  {{- end }}
