apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "ticketdesk.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwt.secret | quote }}
  db-password: {{ include "ticketdesk.mysql.password" . | quote }}
  db-root-password: {{ .Values.mysql.rootPassword | quote }}
  redis-password: {{ include "ticketdesk.redis.password" . | quote }}
  {{- if .Values.nightingale.enabled }}
  n9e-token: {{ .Values.nightingale.token | quote }}
  {{- end }}
