// Package service 提供首次部署初始化向导的业务逻辑
//
// 边界：这里只处理"数据库之后"的配置 —— 管理员账号、站点信息、平台语言。
// 数据库/Redis/JWT 这类"怎么连上库"的配置必须在库外，由配置文件与环境变量提供，
// 多副本下它们的唯一体面归宿是 K8s Secret，不在向导范围内。
package service

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"errors"
	"os"
	"strings"
	"sync/atomic"

	"go.uber.org/zap"
	"golang.org/x/crypto/bcrypt"
	"gorm.io/gorm"

	"github.com/kerbos/ticketdesk/internal/model"
	"github.com/kerbos/ticketdesk/internal/setup/dto"
	configService "github.com/kerbos/ticketdesk/internal/system-config/service"
	"github.com/kerbos/ticketdesk/pkg/logger"
)

// setupTokenEnv 由部署方提供 token 的环境变量。
// K8s 场景走这条：Helm 生成后放进 Secret，所有副本拿到同一个值，
// 既没有生成竞态，也不用去翻某个 Pod 的日志。
const setupTokenEnv = "SETUP_TOKEN"

var (
	// ErrAlreadyInitialized 已经初始化过
	ErrAlreadyInitialized = errors.New("setup.already_initialized")
	// ErrBadToken 初始化令牌不正确
	ErrBadToken = errors.New("setup.bad_token")
)

// Service 初始化向导服务
type Service interface {
	// Initialized 是否已完成初始化
	Initialized(ctx context.Context) bool
	// Setup 执行初始化
	Setup(ctx context.Context, req *dto.SetupRequest) error
	// EnsureToken 确保存在可用的 token；自动生成时把明文打进启动日志
	EnsureToken(ctx context.Context)
}

type setupService struct {
	db        *gorm.DB
	configSvc configService.ConfigService
	// done 一旦为 true 就不再回源查库。
	// 只会 false → true 单向翻转，所以用 atomic.Bool 足够，不需要锁。
	done atomic.Bool
}

// NewService 创建初始化向导服务
func NewService(db *gorm.DB, configSvc configService.ConfigService) Service {
	return &setupService{db: db, configSvc: configSvc}
}

// Initialized 是否已完成初始化
//
// 多副本下 A 完成初始化后 B 仍持有旧的 false，所以未完成时每次都回源。
//
// 刻意绕开 configService 直接读库：初始化标志是迁移阶段用 GORM 直写的，
// 不经过配置服务，缓存里可能留着上一轮的旧值 —— 那会让一个已经初始化好的实例
// 一直对外返回 503。这里是单行主键读，而且只在初始化完成前发生
// （done 一旦置位就永远短路），不值得为它引入缓存一致性的负担。
func (s *setupService) Initialized(ctx context.Context) bool {
	if s.done.Load() {
		return true
	}
	if s.readConfigDirect(ctx, configService.KeySetupCompleted) == "1" {
		s.done.Store(true)
		return true
	}
	return false
}

// readConfigDirect 不走缓存地读一行配置；读不到返回空串
func (s *setupService) readConfigDirect(ctx context.Context, key string) string {
	var cfg model.SystemConfig
	err := s.db.WithContext(ctx).Where("config_key = ?", key).First(&cfg).Error
	if err == nil {
		return cfg.ConfigValue
	}
	if !errors.Is(err, gorm.ErrRecordNotFound) {
		// 数据库读不了时保守地当作"已初始化"：宁可让向导打不开，
		// 也不能因为一次抖动把一个在跑的实例暴露成可被重新初始化
		logger.Warn("failed to read setup config, assuming initialized", zap.String("key", key), zap.Error(err))
		return "1"
	}
	return ""
}

// EnsureToken 确保存在可用的 token
//
// 优先用环境变量；没有则自动生成一个，明文只在此刻打进日志，库里只存哈希。
// 多副本同时生成时靠 config_key 唯一约束定胜负，落败的副本不打印明文
// —— 它手上只有自己那个作废了的值，打出来会误导运维。
func (s *setupService) EnsureToken(ctx context.Context) {
	if s.Initialized(ctx) {
		return
	}
	if strings.TrimSpace(os.Getenv(setupTokenEnv)) != "" {
		logger.Info("setup pending, using token from environment")
		return
	}

	if s.readConfigDirect(ctx, configService.KeySetupTokenHash) != "" {
		logger.Info("setup pending, token already generated by another replica (see its startup logs)")
		return
	}

	buf := make([]byte, 24)
	if _, err := rand.Read(buf); err != nil {
		logger.Error("failed to generate setup token", zap.Error(err))
		return
	}
	token := hex.EncodeToString(buf)

	cfg := &model.SystemConfig{
		ConfigKey:   configService.KeySetupTokenHash,
		ConfigValue: hashToken(token),
		ConfigType:  "string",
		Category:    configService.CategorySetup,
		Description: "初始化令牌哈希",
		IsSecret:    true,
	}
	// Create 而不是 Upsert：并发时让唯一约束选出唯一的赢家
	if err := s.db.WithContext(ctx).Create(cfg).Error; err != nil {
		logger.Info("setup pending, token already generated by another replica (see its startup logs)")
		return
	}

	logger.Warn("================ TicketDesk 尚未初始化 ================")
	logger.Warn("请用下面的令牌打开初始化向导（此令牌只在本次日志出现一次）")
	logger.Warn("setup token: " + token)
	logger.Warn("======================================================")
}

// Setup 执行初始化
//
// 全程一个事务：建管理员、授管理员角色、写站点配置、翻初始化标志。
// 任何一步失败都整体回滚，不会留下"有管理员但没标记完成"这种中间态。
func (s *setupService) Setup(ctx context.Context, req *dto.SetupRequest) error {
	if s.Initialized(ctx) {
		return ErrAlreadyInitialized
	}
	if err := s.verifyToken(ctx, req.Token); err != nil {
		return err
	}

	hashed, err := bcrypt.GenerateFromPassword([]byte(req.Password), bcrypt.DefaultCost)
	if err != nil {
		return err
	}

	err = s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// 先抢标志位：并发提交时只有一个副本能把 0 改成 1，
		// 其余的 RowsAffected 为 0，直接失败退出，不会建出第二个管理员
		res := tx.Model(&model.SystemConfig{}).
			Where("config_key = ? AND config_value <> ?", configService.KeySetupCompleted, "1").
			Update("config_value", "1")
		if res.Error != nil {
			return res.Error
		}
		if res.RowsAffected == 0 {
			return ErrAlreadyInitialized
		}

		admin := &model.User{
			Username:     req.Username,
			Email:        req.Email,
			PasswordHash: string(hashed),
			DisplayName:  req.DisplayName,
			Status:       1,
			Locale:       req.Language,
		}
		if err := tx.Create(admin).Error; err != nil {
			return err
		}

		var role model.Role
		if err := tx.Where("name = ?", "admin").First(&role).Error; err != nil {
			return err
		}
		if err := tx.Create(&model.UserRole{UserID: admin.ID, RoleID: role.ID}).Error; err != nil {
			return err
		}

		for key, value := range map[string]string{
			configService.KeyGeneralSiteURL:  req.SiteURL,
			configService.KeyGeneralLanguage: req.Language,
			configService.KeyBrandSystemName: req.SystemName,
		} {
			if err := upsertConfig(tx, key, value); err != nil {
				return err
			}
		}

		// token 用过即弃
		return tx.Where("config_key = ?", configService.KeySetupTokenHash).
			Delete(&model.SystemConfig{}).Error
	})
	if err != nil {
		return err
	}

	s.done.Store(true)
	// 配置缓存里还留着初始化前的旧值，不清掉的话本副本会继续读到空的站点域名
	_ = s.configSvc.InvalidateAllCache(ctx)
	logger.Info("setup completed", zap.String("admin", req.Username))
	return nil
}

// verifyToken 校验初始化令牌
//
// 用常数时间比较：这个接口在初始化完成前是公开的，
// 逐字节短路的比较会把令牌长度和前缀通过响应时间泄露出去。
func (s *setupService) verifyToken(ctx context.Context, provided string) error {
	if envToken := strings.TrimSpace(os.Getenv(setupTokenEnv)); envToken != "" {
		if subtle.ConstantTimeCompare([]byte(provided), []byte(envToken)) == 1 {
			return nil
		}
		return ErrBadToken
	}

	stored := s.readConfigDirect(ctx, configService.KeySetupTokenHash)
	if stored == "" || stored == "1" {
		return ErrBadToken
	}
	if subtle.ConstantTimeCompare([]byte(hashToken(provided)), []byte(stored)) == 1 {
		return nil
	}
	return ErrBadToken
}

func hashToken(token string) string {
	sum := sha256.Sum256([]byte(token))
	return hex.EncodeToString(sum[:])
}

// upsertConfig 写配置；向导跑在事务里，不能走 configService（它自带缓存与独立连接）
func upsertConfig(tx *gorm.DB, key, value string) error {
	res := tx.Model(&model.SystemConfig{}).
		Where("config_key = ?", key).
		Update("config_value", value)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected > 0 {
		return nil
	}
	category := key
	if i := strings.Index(key, "."); i > 0 {
		category = key[:i]
	}
	return tx.Create(&model.SystemConfig{
		ConfigKey:   key,
		ConfigValue: value,
		ConfigType:  "string",
		Category:    category,
	}).Error
}
